# Generated by Django 5.2.14 on 2026-05-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_partner', '0001_initial'),
        ('financials', '0002_apikey_encrypted_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='endpoint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='response_time_ms',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('secret_key', models.CharField(max_length=255)),
                ('subscribed_event', models.CharField(choices=[('health.updated', 'health.updated'), ('company.updated', 'company.updated'), ('sector.updated', 'sector.updated')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='financials.channelpartner')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api_partner.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
