# Generated by Django 5.2.14 on 2026-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('sector_id', models.IntegerField()),
                ('roe_percentage', models.FloatField(null=True)),
                ('roce_percentage', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLScores',
            fields=[
                ('symbol', models.CharField(max_length=20)),
                ('health_score', models.FloatField()),
                ('rating', models.CharField(max_length=20)),
                ('computed_at', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLScoresLatest',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('health_score', models.FloatField()),
                ('rating', models.CharField(max_length=20)),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fact_ml_scores_latest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dim_sector',
                'managed': False,
            },
        ),
    ]
