# Generated by Django 5.2.14 on 2026-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('year_id', models.IntegerField()),
                ('anomaly_z_any', models.BooleanField()),
                ('anomaly_iso', models.IntegerField()),
                ('final_anomaly', models.BooleanField()),
            ],
            options={
                'db_table': 'fact_anomalies',
                'managed': False,
            },
        ),
    ]
