# Generated by Django 5.2.14 on 2026-05-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='encrypted_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
