# Generated by Django 5.2.14 on 2026-05-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('health_score', models.FloatField(default=0)),
                ('roe', models.FloatField(default=0)),
                ('debt_to_equity', models.FloatField(default=0)),
                ('current_ratio', models.FloatField(default=0)),
                ('revenue_growth', models.FloatField(default=0)),
                ('profit_growth', models.FloatField(default=0)),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
