# Generated by Django 5.2.14 on 2026-05-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
    ]
