# Generated by Django 5.2.14 on 2026-05-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='dim_company',
        ),
    ]
