# Generated by Django 5.2.14 on 2026-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.TextField()),
                ('year', models.BigIntegerField()),
                ('equity_capital', models.FloatField()),
                ('reserves', models.BigIntegerField()),
                ('borrowings', models.BigIntegerField()),
                ('other_liabilities', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('fixed_assets', models.BigIntegerField()),
                ('cwip', models.BigIntegerField()),
                ('investments', models.BigIntegerField()),
                ('other_asset', models.BigIntegerField()),
                ('total_assets', models.BigIntegerField()),
                ('date', models.TextField()),
                ('month', models.BigIntegerField()),
                ('year_id', models.BigIntegerField()),
                ('de_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.TextField()),
                ('year', models.BigIntegerField()),
                ('sales', models.BigIntegerField()),
                ('expenses', models.BigIntegerField()),
                ('operating_profit', models.FloatField()),
                ('opm_percentage', models.FloatField()),
                ('other_income', models.BigIntegerField()),
                ('interest', models.BigIntegerField()),
                ('depreciation', models.BigIntegerField()),
                ('profit_before_tax', models.BigIntegerField()),
                ('tax_percentage', models.FloatField()),
                ('net_profit', models.BigIntegerField()),
                ('eps', models.FloatField()),
                ('dividend_payout', models.FloatField()),
                ('date', models.TextField()),
                ('month', models.BigIntegerField()),
                ('year_id', models.IntegerField()),
                ('opm_pct', models.FloatField()),
                ('profit_margin', models.FloatField()),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': False,
            },
        ),
    ]
